spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springdemo?useUnicode=true&characterEncoding=utf8&autoReconnect=true
    username: root
    password: 111111
debug: true
mybatis:
  type-aliases-package: com.springdemo.model
  config-location: classpath:mybatis.xml
